##############################################################################
# Copyright 2022-2025 Leon Lynch
#
# This file is licensed under the terms of the LGPL v2.1 license.
# See LICENSE file.
##############################################################################

name: MacOS build

on: [push]

jobs:
  build-macos-debug:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "MacOS 13", os: macos-13, osx_arch: "x86_64;arm64", build_type: "Debug", fetch_deps: YES }
          - { name: "MacOS 13", os: macos-13, osx_arch: "x86_64", build_type: "Release", fetch_deps: NO }
          - { name: "MacOS 14", os: macos-14, osx_arch: "arm64", build_type: "Debug", fetch_deps: NO }
          - { name: "MacOS 14", os: macos-14, osx_arch: "x86_64;arm64", build_type: "Release", fetch_deps: YES }

    name: ${{ matrix.name }} build (static/${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      # Homebrew doesn't support universal binaries so only install dependencies for arch-specific builds
      if: ${{ matrix.fetch_deps == 'NO' }}
      run: |
        brew install mbedtls
        brew install argp-standalone
        echo "CMAKE_REQUIRE_FIND_PACKAGE_MbedTLS=YES" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: git describe --always --dirty

    - name: Configure CMake
      run: cmake -B build -DCMAKE_OSX_ARCHITECTURES="${{ matrix.osx_arch }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -DFETCH_MBEDTLS=${{ matrix.fetch_deps }} -DCMAKE_REQUIRE_FIND_PACKAGE_MbedTLS=${{ env.CMAKE_REQUIRE_FIND_PACKAGE_MbedTLS }} -DFETCH_ARGP=${{ matrix.fetch_deps }}

    - name: Build
      run: cmake --build build -j 4

    - name: Test
      run: ctest --test-dir build --output-on-failure -j 4
